"""Add user profile picture fields

Revision ID: 775559961b53
Revises: bbdf137a825d
Create Date: 2026-05-23 10:23:10.272869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775559961b53'
down_revision = 'bbdf137a825d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('profile_pic_public_id', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic_public_id')
        batch_op.drop_column('profile_pic_url')

    # ### end Alembic commands ###
