"""add module quiz completions table

Revision ID: 9b2712390a91
Revises: 775559961b53
Create Date: 2026-06-13 10:44:54.614263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2712390a91'
down_revision = '775559961b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_quiz_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_user_module_quiz')
    )
    with op.batch_alter_table('module_quiz_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_quiz_completions_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_quiz_completions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_quiz_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_quiz_completions_user_id'))
        batch_op.drop_index(batch_op.f('ix_module_quiz_completions_module_id'))

    op.drop_table('module_quiz_completions')
    # ### end Alembic commands ###
