"""Add module thumbnail fields

Revision ID: bbdf137a825d
Revises: 1fcfdbe43be0
Create Date: 2026-05-23 10:04:15.314163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdf137a825d'
down_revision = '1fcfdbe43be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_public_id', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_public_id')
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###
