"""add optional modules field

Revision ID: fb5bef3b55ee
Revises: 9b2712390a91
Create Date: 2026-06-13 11:09:26.519037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5bef3b55ee'
down_revision = '9b2712390a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_optional', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_column('is_optional')

    # ### end Alembic commands ###
